-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 00:08:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Meu_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Meu_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Meu_banco` DEFAULT CHARACTER SET utf8 ;
USE `Meu_banco` ;

-- -----------------------------------------------------
-- Table `Meu_banco`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meu_banco`.`Estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_nota_fiscal` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `desconto` INT NOT NULL,
  PRIMARY KEY (`id`, `id_produto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
